version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./nginx-certs:/etc/nginx/certs
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: amiroso
      POSTGRES_PASSWORD: 'amiroso1236@/'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: amiroso
      RABBITMQ_DEFAULT_PASS: 'amiroso'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  postgres:
  rabbitmq:
