version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: amiroso
      POSTGRES_PASSWORD: 'amiroso1236@/'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: amiroso
      RABBITMQ_DEFAULT_PASS: 'amiroso'
    ports:
      - '5672:5672' # RabbitMQ default port
      - '15672:15672' # RabbitMQ management console
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  postgres:
  rabbitmq:
